### ISSUE TITLE
Feature : Show image name in container list

### ISSUE THREAD

**Issue by ggrimbert** [formulahendry/vscode-docker-explorer#10]
This could be interested to have a "property" option in the contextual menu that show the same infos as "docker ps".

For example, in my case, I use many containers that are not renamed, so it's hard to know what image is linked.

And maybe, show too the image name in the tree explorer.

**Comment by formulahendry** [comment]
Currently, if you click on the container, the 'docker ps' will be shown in terminal output.
But I think it would be good to include image name in container list.

Current container list in tree explorer:
-- container_1 
-- container_2
-- container_3

Change to:
-- container_1 (image_name_1)
-- container_2 (image_name_2)
-- container_3 (image_name_3)

What do you think?

**Comment by ggrimbert** [comment]
Yes, this is a good idea.

**Comment by formulahendry** [comment]
Image names are shown in container list now.
