### ISSUE TITLE
Please provide a way to disable unused panels: Azure Container Registry, Docker Hub, and Suggested Docker Hub Images

### ISSUE THREAD

**Issue by aharpervc** [formulahendry/vscode-docker-explorer#22]
Since the latest update, 3 new panels show up and there is no apparent way to disable them. Please provide an option to disable these panels.

**Comment by formulahendry** [comment]
Please wait for the VS Code v1.15 released this week. Then you will be able to hide any panel you want: https://github.com/Microsoft/vscode/issues/30120

**Comment by batjko** [comment]
Yea took me by surprise as well. I don't use any of those registry panels.
And I wasn't aware that vscode ticket is coming soon (I didn't see any release date for that, but I'll assume @formulahendry is right), so hopefully that will fix the issue asap.

**Comment by formulahendry** [comment]
@batjko You could see the release date here: https://github.com/Microsoft/vscode/issues/31333

**Comment by batjko** [comment]
@formulahendry Yes, It's just that the 4th Aug has come and gone and there are still a few issues they have yet to take care of, according to that list.

But I'm sure it'll be ready in a few days or a week or so.

**Comment by formulahendry** [comment]
@aharpervc @batjko , please check out the new version of VS Code: https://code.visualstudio.com/updates/v1_15#_managing-views

**Comment by aharpervc** [comment]
This is fine to remove the panels from existing windows. But every time I open up a new folder in a separate window, ALL the panels show up, and I have to remove them one by one. A configuration preference for which panels should show up by default would still be nice.

**Comment by formulahendry** [comment]
@aharpervc I just create an [issue](https://github.com/Microsoft/vscode/issues/32357) for VS Code. Let's wait for their feedback and suggestion.

**Comment by formulahendry** [comment]
Added option to show or hide different explorers, please install the latest version and update the config: https://github.com/formulahendry/vscode-docker-explorer#visibility-of-docker-explorer
