### ISSUE TITLE
Allow for sorting of containers

### ISSUE THREAD

**Issue by mrpotatoes** [formulahendry/vscode-docker-explorer#30]
It would be nice to have the greens at the top so I don't have to search a giant list of containers. Perhaps by name or allow me to pass a callback for how to sort.

![screen shot 2018-02-26 at 11 06 31 am](https://user-images.githubusercontent.com/1066744/36680938-2b98b060-1ae5-11e8-9bd8-1c10b8fb9931.png)

Cheers

**Comment by chris-aeviator** [comment]
:+1: for me - I'm primarily using docker-compose to run my projects and use the Docker Explorer extension to attach/log to only running containers. Adding a config variable to hide stopped containers would be a valid usecase in my opinion.
