### ISSUE TITLE
find containers using ⌘ + p

### ISSUE THREAD

**Issue by AlexZeitler** [formulahendry/vscode-docker-explorer#4]
First things first: thanks for this extension 👍 

It would be great to find containers using `⌘ + p` like files.

**Comment by formulahendry** [comment]
Thanks @AlexZeitler for your feedback! Is the below flow what you want?

1. Use keyboard shortcut to pop up a search window (We could not use `⌘ + p`, but I could provide another key binding, and you could customize yourself)
2. Type the container name (or other? e.g. image name? ) to search
3. Select the container
4. Run `docker ps --filter "id={contain_id}"` to show container info in terminal (Just like the result that your click on the container in the Container Tree Explorer)

**Comment by AlexZeitler** [comment]
@formulahendry Yes, this would be great.

If you're building your own search dialog, it would cool if you could have shortcuts like `⌘ + D` to switch to the Docker context and with `⌘ + I` you could list images or with `⌘ + D` (again) you could list containers (`⌘ + D` because `⌘ + C` is blocked by Copy/Paste.

**Comment by formulahendry** [comment]
In short-term, let' focus on containers management first. Feature for images will be addressed in #2

**Comment by AlexZeitler** [comment]
Yes, thats ok

**Comment by formulahendry** [comment]
It is supported in latest version. Also, you could define the key binding for "docker-explorer.searchContainer" yourself. Refer to https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor

![image](https://user-images.githubusercontent.com/1050213/27287545-a41e3692-5536-11e7-99e9-26ec39244766.png)

**Comment by AlexZeitler** [comment]
Thanks for your fast implementation but I can't find the shortcut settings or the command in the command list. 
I'm using `0.0.6` and I tried re-installing it but settings don't appear.

**Comment by formulahendry** [comment]
Click the `...`, you should see the `Search` command.
![image](https://user-images.githubusercontent.com/1050213/27419484-c73612f2-5753-11e7-8094-0e3dd00ffa92.png)

**Comment by AlexZeitler** [comment]
@formulahendry Thanks, now it works! 👍
