### ISSUE TITLE
Auto-refresh status

### ISSUE THREAD

**Issue by batjko** [formulahendry/vscode-docker-explorer#5]
First of all: Great extension. It's really useful already!

When I start Code while no containers are running, the extension shows the ones I have hanging around and correctly as inactive.
However, if I then start them (I use docker-compose to start a whole stack during development), the icons don't automatically update to show the containers coming online.
Only after I click the Refresh button will they update.

Would be nice if I could rely on the icons to be "live".

Cheers.

**Comment by formulahendry** [comment]
Released in v0.0.3
