### ISSUE TITLE
Run as super user

### ISSUE THREAD

**Issue by ggrimbert** [formulahendry/vscode-docker-explorer#9]
Hi,

I think you should add an option to allow running the extension as super user and prompts for password.

In my configuration, docker is installed from apt-get, so all commands have to be run as super user (ubuntu).

**Comment by formulahendry** [comment]
Hi @ggrimbert , two questions here:
1. Are the Docker Containers shown correctly in the Tree Explorer?
2. Do you want to prepend `sudo` for each command? e.g. change `docker start {containerId}` with `sudo docker start {containerId}`

**Comment by ggrimbert** [comment]
Nothing is shown in tree explorer. In the apt-get installation of docker, the linux socket is assigned to root, so everything has to be runned with sudo.

So yes, I wish the sudo for each command.

**Comment by formulahendry** [comment]
Hi @ggrimbert , here I find a workaround to run Docker without 'sudo': https://docs.docker.com/engine/installation/linux/linux-postinstall/#manage-docker-as-a-non-root-user . You could have try. Let me know whether it works well.

**Comment by ggrimbert** [comment]
Thanks for the working workaround !
Now, everything's OK. 

To avoid opening a new issue for a feature request, I post here. Is it possible to add a properties option in contextual menu, or add at least the image name in the explorer ? I run / stop multiple images and I don't rename them, with just the name of the container it's a bit hard to see what container is the one I want.

**Comment by formulahendry** [comment]
Feel free to open a separate issue. That would be good to track. 😃

**Comment by ggrimbert** [comment]
Ok I close this one.

Thanks again for your quick answer !
